### ISSUE TITLE
Mybb  1.8

### ISSUE THREAD

**Issue by Amandeeptamber** [vBZachery/vbimpex#2]
Can you please add mybb 1.8 to the systems as its showing mybb 1.4 in the import and after using it i am getting error while importing users.

**Comment by vBZachery** [comment]
I will do my best to look into updating it. But I cannot make any hard promises.

Can you please provide any specific examples of issues you're facing?

**Comment by vBZachery** [comment]
Do me a favor, in the systems/impex/mybb folder, in 004.php find

```
        $try->set_value('nonmandatory', 'ipaddress',            $user_details['regip']);
```

Change too

```
        $zREGIP = long2ip($user_details['regip']);
        $try->set_value('nonmandatory', 'ipaddress',            $zREGIP);
```

I don't currently have a mybb database to test, and don't have the time to try it right now. Let me know if it fixes/breaks anything.

Might need more fixes in the post importing

**Comment by Amandeeptamber** [comment]
Great Zachery :) That fix worked :)

**Comment by Amandeeptamber** [comment]
Everything imported except moderators( i will do that manually) and attachments. How to import the attachments?

**Comment by vBZachery** [comment]
Can you let me know how moderators, and attachments didn't import?

How does mybb currently store attachments?

**Comment by Amandeeptamber** [comment]
Mybb store the attachments in /uploads folder with year and month name folders inside. Like year 2010 month October, then it saves the attachments of October 2010 to folder name 201010 and so on.

**Comment by vBZachery** [comment]
When you ran the attachment importer, did you give the full system path to your attachments?

**Comment by Amandeeptamber** [comment]
I give the path like this /uploads

**Comment by vBZachery** [comment]
Can you please use the full system path. If you don't know what that is please contact your web host

Sent from my Windows Phone

**Comment by MaskUp** [comment]
You can create a .php file with the contents below and navagate your browser to it to find your forums path. I use this code from vbadvanced.

```
 <?php

if ($_SERVER['PATH_TRANSLATED'])
{
    $path = $_SERVER['PATH_TRANSLATED'];
}
else if ($_SERVER['SCRIPT_FILENAME'])
{
    $path = $_SERVER['SCRIPT_FILENAME'];
}
else
{
    echo 'We are sorry, but this script is unable to determine your forums path.';
    exit;
}

echo substr($path, 0, (strlen($path) - 14));

?> 
```

**Comment by Amandeeptamber** [comment]
Ok thanks, will check. Is it
Possible to import reputation of users and thanks data from mybb thank you
like plugin to Vbulletin reputation system and Vbulletin 4.2 thanks plugin?

**Comment by vBZachery** [comment]
At this time its not. Were you able to re-run the attachment import, did it work?

**Comment by Amandeeptamber** [comment]
Yes it worked when i found the correct attachment path. All attachments imported :)
Marking this issue as resolved.

**Comment by vBZachery** [comment]
I will push changes for mybb this week

Sent from my Windows Phone
