### ISSUE TITLE
Does Impex support Gossamer Forums?

### ISSUE THREAD

**Issue by jeffwidman** [vBZachery/vbimpex#3]
I'm looking for an import script for an old forum running Gossamer Forums... While it's not listed in the VB.com manual, I found an old VB.com thread that says Impex supports Gossamer Forums: 

http://www.vbulletin.com/forum/forum/vbulletin-4/vbulletin-impex-import-system/253526-import-gossamer-forum

Is this true? Hoping to save myself a ton of work...

**Comment by vBZachery** [comment]
Hi Jeff, sorry it took me a bit to respond, I didn't get a notification for this.

There is a gossamer_threads system in impex. It looks like there is support for 1.2.4

``` php
var $_version = '1.2.4';
    var $_tested_versions = array('1.2.4');
```

**Comment by jeffwidman** [comment]
Thanks!

Is there a filename/line number where I can look at the code? 

I searched but not finding `_tested_versions` anywhere in this repo... Just want to look through the code before I actually try and run it.

**Comment by vBZachery** [comment]
systems/gossamer_threads/

**Comment by vBZachery** [comment]
Please feel free to re-open if you're having issues or further questions

**Comment by jeffwidman** [comment]
Many thanks. I'll have to dig into it a bit and see how it goes.
