### ISSUE TITLE
Cback support

### ISSUE THREAD

**Issue by kevinwalter** [vBZachery/vbimpex#4]
Hi,

We've got a forum that is running for 11 years. But we need something else.

The forum runs on cback. (www.cback.de) I'm trying to move to vbulletin or so. But no one has support for a cback conversion.
I can, if needed, give you a clean cback database dump with 2 users or so.

**Comment by vBZachery** [comment]
What do you want to import? Just users? Or more than users?

**Comment by kevinwalter** [comment]
HI Zachery,

Thanks you for your answer!
I want to import the posts/topics, Users/passwords/profiles if this is possible, signatures and forums.

**Comment by vBZachery** [comment]
Can you get me a SQL with some example data in it?

**Comment by kevinwalter** [comment]
Yes, I can. How can I send it to you?

**Comment by vBZachery** [comment]
Sorry for the very late reply, I don't have time to develop a new importer. But good luck, if you did find any one who developed this and they want to release it back here I'm happy to merge it.
